import { Options } from '../components/SelectPlace'

export const PLACES: Options = [
  {
    value: 'berlin',
    label: 'Berlin',
    country: 'DE',
    longitude: 13.4115,
    latitude: 52.5235,
    timezone: 'Europe/Berlin',
  },
  {
    value: 'brasilia',
    label: 'Brasilia',
    country: 'BR',
    longitude: -47.9292,
    latitude: -15.7801,
    timezone: 'America/Sao_Paulo',
  },
  {
    value: 'brussels',
    label: 'Brussels',
    country: 'HU',
    longitude: 4.3676,
    latitude: 50.8371,
    timezone: 'Europe/Berlin',
  },
  {
    value: 'canberra',
    label: 'Canberra',
    country: 'AU',
    longitude: 149.1286,
    latitude: -35.282,
    timezone: 'Australia/Sydney',
  },
  {
    value: 'dublin',
    label: 'Dublin',
    country: 'IE',
    longitude: -6.2675,
    latitude: 53.3441,
    timezone: 'Europe/London',
  },
  {
    value: 'london',
    label: 'London',
    country: 'UK',
    longitude: -0.1262,
    latitude: 51.5002,
    timezone: 'Europe/London',
  },
  {
    value: 'madrid',
    label: 'Madrid',
    country: 'ES',
    longitude: -3.7033,
    latitude: 40.4167,
    timezone: 'Europe/Berlin',
  },
  {
    value: 'moscow',
    label: 'Moscow',
    country: 'RU',
    longitude: 37.6176,
    latitude: 55.7558,
    timezone: 'Europe/Moscow',
  },
  {
    value: 'nairobi',
    label: 'Nairobi',
    country: 'KE',
    longitude: 36.7965,
    latitude: -1.2762,
    timezone: 'Africa/Cairo',
  },
  {
    value: 'new-york',
    label: 'New York',
    country: 'US',
    longitude: -74.01,
    latitude: 40.71,
    timezone: 'America/New_York',
  },

  {
    value: 'paris',
    label: 'Paris',
    country: 'FR',
    longitude: 2.351,
    latitude: 48.8567,
    timezone: 'Europe/Berlin',
  },
  {
    value: 'reykjavík',
    label: 'Reykjavík',
    country: 'IS',
    longitude: -21.8952,
    latitude: 64.1353,
    timezone: 'Atlantic/Reykjavik',
  },
  {
    value: 'rome',
    label: 'Rome',
    country: 'IT',
    longitude: 12.4823,
    latitude: 41.8955,
    timezone: 'Europe/Berlin',
  },
  {
    value: 'stockholm',
    label: 'Stockholm',
    country: 'SE',
    longitude: 18.0645,
    latitude: 59.3328,
    timezone: 'Europe/Stockholm',
  },
  {
    value: 'tokyo',
    label: 'Tokyo',
    country: 'JP',
    longitude: 139.6823,
    latitude: 35.6785,
    timezone: 'Asia/Tokyo',
  },
  {
    value: 'vancouver',
    label: 'Vancouver',
    country: 'CA',
    longitude: -123.12,
    latitude: 49.25,
    timezone: 'America/Vancouver',
  },
  {
    value: 'vienna',
    label: 'Vienna',
    country: 'AU',
    longitude: 16.3728,
    latitude: 48.2092,
    timezone: 'Europe/Berlin',
  },
  {
    value: 'washington',
    label: 'Washington',
    country: 'US',
    longitude: -77.0241,
    latitude: 38.8921,
    timezone: 'America/New_York',
  },
]
