export const WEATHER_INFOS = {
  placeName: '',
  country: '',
  latitude: 0,
  longitude: 0,
  hourly: {
    time: [''],
    temperature_2m: [],
    precipitation: [],
    snowfall: [],
    cloudcover: [],
    windspeed: [],
    weathercode: [],
    apparent_temperature: [],
  },
  current_weather: { time: '', temperature: 0, windspeed: 0 },
  daily: {
    temperature_2m_max: [],
    temperature_2m_min: [],
    precipitation_sum: [],
    sunrise: [],
    sunset: [],
    windspeed_10m_max: [],
    snowfall_sum: [],
    weathercode: [],
  },
  dailyINFOS: {
    temperature_2m_max: [],
    temperature_2m_min: [],
    precipitation_sum: [],
    sunrise: [],
    sunset: [],
    windspeed_10m_max: [],
    snowfall_sum: [],
    weathercode: [],
  },
  hourlyINFOS: {
    time: [''],
    temperature_2m: [],
    precipitation: [],
    snowfall: [],
    cloudcover: [],
    windspeed: [],
    weathercode: [],
    apparent_temperature: [],
    relativehumidity_2m: [],
  },
}
